name: Skyline

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master
    
jobs:

  deploy-webgl-site:
    
    runs-on: windows-2019
    if: "contains(github.event.head_commit.message, '[deploy site]')"

    steps:

    - uses: actions/checkout@v2
      
    - name: Deploy Site
      shell: cmd
      run: |
        git fetch
        
        Xcopy .\Skyline ..\ /e /h /c /i
        git checkout gh-pages
        cd ..
        cd public
        Xcopy . ..\Skyline\ /e /h /c /i /y
        cd ..
        cd Marvel
        git config --global user.email "jonathanhoffstadt@yahoo.com"
        git config --global user.name "Jonathan Hoffstadt"
        git commit -a -m "Update site"
        git push origin gh-pages -q
        